requires 'Kossy', '0.40';
requires 'DBIx::Sunny';
requires 'DBD::mysql';
requires 'LWP::UserAgent';
requires 'List::MoreUtils';
requires 'JSON';
requires 'URI';
requires 'String::Random';
requires 'Digest::SHA1';
requires 'Path::Tiny';
requires 'Plack::App::Proxy';
requires 'Plack::Session';
requires 'Starlet';
requires 'Furl';
requires 'Proclet';
requires 'Cache::Memcached::Fast';
requires 'Devel::KYTProf';
